"""add_debate_messages

Revision ID: 4b3645503a6d
Revises: 8c4523d340aa
Create Date: 2026-06-11 19:24:46.439292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b3645503a6d'
down_revision: Union[str, Sequence[str], None] = '8c4523d340aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('debate_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('debate_id', sa.Integer(), nullable=True),
    sa.Column('round', sa.Integer(), nullable=True),
    sa.Column('agent', sa.String(), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('evidence_refs', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['debate_id'], ['debates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_debate_messages_id'), 'debate_messages', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_debate_messages_id'), table_name='debate_messages')
    op.drop_table('debate_messages')
    # ### end Alembic commands ###
