"""add_reconciliation_unit_fields

Revision ID: 65513c872d31
Revises: 3b0260368a71
Create Date: 2026-06-11 18:00:31.249181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65513c872d31'
down_revision: Union[str, Sequence[str], None] = '3b0260368a71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reconciliation_units', sa.Column('diff_hunk', sa.String(), nullable=True))
    op.add_column('reconciliation_units', sa.Column('upstream_commits', sa.JSON(), nullable=True))
    op.add_column('reconciliation_units', sa.Column('fork_commits', sa.JSON(), nullable=True))
    op.add_column('reconciliation_units', sa.Column('complexity_score', sa.Float(), nullable=True))
    op.add_column('reconciliation_units', sa.Column('severity_score', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reconciliation_units', 'severity_score')
    op.drop_column('reconciliation_units', 'complexity_score')
    op.drop_column('reconciliation_units', 'fork_commits')
    op.drop_column('reconciliation_units', 'upstream_commits')
    op.drop_column('reconciliation_units', 'diff_hunk')
    # ### end Alembic commands ###
