"""phase2_debate_tables

Revision ID: b7ee7cc1d052
Revises: 65513c872d31
Create Date: 2026-06-11 18:11:44.316008

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = 'b7ee7cc1d052'
down_revision: Union[str, Sequence[str], None] = '65513c872d31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
