"""add_debate_metrics

Revision ID: fc73863a71f5
Revises: 4b3645503a6d
Create Date: 2026-06-11 21:05:47.600693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc73863a71f5'
down_revision: Union[str, Sequence[str], None] = '4b3645503a6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('debates', sa.Column('architectural_proposal', sa.String(), nullable=True))
    op.add_column('debates', sa.Column('consensus_score', sa.Float(), nullable=True))
    op.add_column('debates', sa.Column('confidence', sa.Float(), nullable=True))
    op.add_column('debates', sa.Column('evidence_count', sa.Integer(), nullable=True))
    op.add_column('debates', sa.Column('verification_score', sa.Float(), nullable=True))
    op.add_column('debates', sa.Column('token_usage', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('debates', 'token_usage')
    op.drop_column('debates', 'verification_score')
    op.drop_column('debates', 'evidence_count')
    op.drop_column('debates', 'confidence')
    op.drop_column('debates', 'consensus_score')
    op.drop_column('debates', 'architectural_proposal')
    # ### end Alembic commands ###
